// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEObACFfF-vnFLJloP-TK9Kz-lI6gMZU',
    appId: '1:930771409692:web:fc0735c04fe4cd6ff6f8d9',
    messagingSenderId: '930771409692',
    projectId: 'lango-application',
    authDomain: 'lango-application.firebaseapp.com',
    storageBucket: 'lango-application.appspot.com',
    measurementId: 'G-BTVDWY1JZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBW8dMmod7NwSF-2KmhO8w0S_luf8rUU',
    appId: '1:930771409692:android:b3ca470789e41febf6f8d9',
    messagingSenderId: '930771409692',
    projectId: 'lango-application',
    storageBucket: 'lango-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlf5fUVebuYarFbxtqDFtgEaMt5Wx_iCQ',
    appId: '1:930771409692:ios:1821ba3e88539a3bf6f8d9',
    messagingSenderId: '930771409692',
    projectId: 'lango-application',
    storageBucket: 'lango-application.appspot.com',
    iosClientId: '930771409692-le7qlk2uiuhgtojq4i7vs1a3cpic4fth.apps.googleusercontent.com',
    iosBundleId: 'com.example.langoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlf5fUVebuYarFbxtqDFtgEaMt5Wx_iCQ',
    appId: '1:930771409692:ios:1821ba3e88539a3bf6f8d9',
    messagingSenderId: '930771409692',
    projectId: 'lango-application',
    storageBucket: 'lango-application.appspot.com',
    iosClientId: '930771409692-le7qlk2uiuhgtojq4i7vs1a3cpic4fth.apps.googleusercontent.com',
    iosBundleId: 'com.example.langoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGEObACFfF-vnFLJloP-TK9Kz-lI6gMZU',
    appId: '1:930771409692:web:f8b628b363da63fdf6f8d9',
    messagingSenderId: '930771409692',
    projectId: 'lango-application',
    authDomain: 'lango-application.firebaseapp.com',
    storageBucket: 'lango-application.appspot.com',
    measurementId: 'G-6M0ETBDV81',
  );
}
